const capitalizeFirstLetter=([first,...rest],locale=navigator.language)=>first.toLocaleUpperCase(locale)+rest.join('');const keyStack=["X","U","S","T","I","N","A","8","9"];var context=document.getElementsByTagName('canvas')[0].getContext('2d');var hue=0;var colourBlender;var disAccepted=false;var gameMode=false;document.body.bgColor="#FFC0C0";function mode_1(evt){evt.preventDefault();evt=evt||window.event;var newKey=evt.key.toUpperCase();var debugString="";var funWordTest="string";var colourString="rgb("+
getRandomInt(0,255)+","+getRandomInt(0,255)+","+getRandomInt(0,255)+")";var randomnumber=getRandomInt(1,3);var colouredKey=false;var wordChecked=false;clearInterval(colourBlender);document.getElementById("gradient").hidden=false;if(newKey==" "){newKey="Space";}
keyStack.push(newKey);keyStack.shift();keyStack.forEach(element=>debugString+=element);document.getElementById("page").hidden=true;document.getElementById("debugtext").innerText=""+debugString;for(var sample in fKeyColours){if(sample==newKey){colouredKey=true;colourString=fKeyColours[sample];}}
funWordTest=""+keyStack[2]+keyStack[3]+keyStack[4]+keyStack[5]+keyStack[6]+keyStack[7]+keyStack[8];if(funWordTest=="JUSTINA"){colourBlender=null;colourBlender=setInterval(bgcolor,10);newKey="<img src='icon.png' alt='Justina's face' /><br />Justina";document.getElementById("page").hidden=false;}
if(colouredKey){newKey=""+fKeyColours[newKey];document.getElementById("gradient").hidden=true;}else{for(let i=0;i<debugString.length;i++){if(!wordChecked){funWordTest=debugString.slice(i,debugString.length).toString();}
for(var test in funWords){var testString=""+test;switch(testString){case funWordTest.toLowerCase():newKey=funWords[funWordTest.toLowerCase()]+"<br />"+testString.toUpperCase();wordChecked=true;break;case funWordTest.toUpperCase():newKey=funWords[funWordTest.toUpperCase()]+"<br />"+testString.toUpperCase();wordChecked=true;break;case capitalizeFirstLetter(funWordTest.toLowerCase()):newKey=funWords[capitalizeFirstLetter(funWordTest.toLowerCase())]+"<br />"+testString.toUpperCase();wordChecked=true;break;}}}
if(wordChecked){for(var sample in fKeyColours){if(capitalizeFirstLetter(fKeyColours[sample].toLowerCase())==capitalizeFirstLetter(funWordTest.toLowerCase())){colourString=fKeyColours[sample];}}
document.getElementById("gradient").hidden=true;}}
document.getElementById("middletext").innerHTML=""+newKey;document.body.style.backgroundColor=""+colourString;document.getElementById("fake").value="";document.getElementById("fake").focus();};function bgcolor(){hue=hue+Math.random()*3;context.fillStyle='hsl('+hue+', 100%, 50%)';context.fillRect(0,0,context.canvas.width,context.canvas.height);}
function getRandomInt(min,max){min=Math.ceil(min);max=Math.floor(max);return Math.floor(Math.random()*(max-min+1))+min;}
function hideDisclaimer(){if(disAccepted){document.getElementById("disclaimer").hidden=true;document.getElementById("fake").focus();}
document.getElementById("disclaimertext").innerHTML="press keys on the keyboard and try to find words";document.getElementById("dTitle").innerHTML="How to Play";disAccepted=true;}
if(gameMode){}
else{document.addEventListener('keydown',mode_1);}
function changeMode(){if(gameMode){document.getElementById("mode_swap").innerHTML="Find All Words";gameMode=false;}else{document.getElementById("mode_swap").innerHTML="Spell The Word";gameMode=true;}}